In [2]:
import numpy as np
import pandas as pd
import sys
df = pd.read_csv('PS4_GamesSales.csv')
df.dropna(0,inplace = True)
df

,Game,Year,Genre,Publisher,North America,Europe,Japan,Rest of World,Global
0,Grand Theft Auto V,2014.0,Action,Rockstar Games,6.06,9.71,0.60,3.02,19.39
1,Call of Duty: Black Ops 3,2015.0,Shooter,Activision,6.18,6.05,0.41,2.44,15.09
2,Red Dead Redemption 2,2018.0,Action-Adventure,Rockstar Games,5.26,6.21,0.21,2.26,13.94
3,Call of Duty: WWII,2017.0,Shooter,Activision,4.67,6.21,0.40,2.12,13.40
4,FIFA 18,2017.0,Sports,EA Sports,1.27,8.64,0.15,1.73,11.80
...,...,...,...,...,...,...,...,...,...
1025,Biomutant,2019.0,Action,THQ Nordic,0.00,0.00,0.00,0.00,0.00
1026,de Blob,2017.0,Platform,THQ Nordic,0.00,0.00,0.00,0.00,0.00
1027,Chaos on Deponia,2017.0,Adventure,Daedalic Entertainment,0.00,0.00,0.00,0.00,0.00
1028,Code Vein,2018.0,Action,Bandai Namco Entertainment,0.00,0.00,0.00,0.00,0.00
1030,Radial G Racing Revolved,2017.0,Racing,Tammeka Games,0.00,0.00,0.00,0.00,0.00

In [4]:
print(np.mean(df))

Year             2015.966061
North America       0.256448
Europe              0.311600
Japan               0.042048
Rest of World       0.111552
Global              0.721721
dtype: float64

In [3]:
#We can also mention the axis along which the mean can be calculated.
print("Mean along axis 0: ", np.mean(df,axis=0))
print("Mean along axis 1: ", np.mean(df,axis=1))

Mean along axis 0:  Year             2015.966061
North America       0.256448
Europe              0.311600
Japan               0.042048
Rest of World       0.111552
Global              0.721721
dtype: float64
Mean along axis 1:  0       342.130000
1       340.861667
2       340.980000
3       340.633333
4       340.098333
           ...
1025    336.500000
1026    336.166667
1027    336.166667
1028    336.333333
1030    336.166667
Length: 825, dtype: float64

In [20]:
print(np.shape(df))
print("Minimum along axis 1: ", np.min(df,axis=1))
print("Minimum along axis 0: ", np.min(df,axis=0))
print("Maximum along axis 0: ", np.max(df,axis=0))
print("Maximum along axis 1: ", np.max(df,axis=1))
print("Standard deviation: ", np.std(df))
print("Variance: ", np.var(df,axis=1))
print("Average: ", np.average(df['Year']))
print("Percentile:", np.percentile(df['Year'],50))

(825, 9)
Minimum along axis 1:  0       0.60
1       0.41
2       0.21
3       0.40
4       0.15
        ...
1025    0.00
1026    0.00
1027    0.00
1028    0.00
1030    0.00
Length: 825, dtype: float64
Minimum along axis 0:  Game             .hack//G.U. Last Recode
Year                              2013.0
Genre                             Action
Publisher                       2K Games
North America                        0.0
Europe                               0.0
Japan                                0.0
Rest of World                        0.0
Global                               0.0
dtype: object
Maximum along axis 0:  Game             theHunter: Call of the Wild
Year                                  2020.0
Genre                           Visual Novel
Publisher                               Yeti
North America                           6.18
Europe                                  9.71
Japan                                   2.17
Rest of World                           3.02
Global                                 19.39
dtype: object
Maximum along axis 1:  0       2014.0
1       2015.0
2       2018.0
3       2017.0
4       2017.0
         ...
1025    2019.0
1026    2017.0
1027    2017.0
1028    2018.0
1030    2017.0
Length: 825, dtype: float64
Standard deviation:  Year             1.297573
North America    0.619883
Europe           0.867745
Japan            0.119741
Rest of World    0.274546
Global           1.742066
dtype: float64
Variance:  0       559065.806467
1       560568.928314
2       562497.590767
3       562057.863456
4       562417.709981
            ...
1025    566161.250000
1026    565040.138889
1027    565040.138889
1028    565600.555556
1030    565040.138889
Length: 825, dtype: float64
Average:  2015.9660606060606
Percentile: 2016.0

In [23]:
print("Range : ", np.ptp(df['Year']))
print("Range : ", np.ptp(df['Global']))

Range :  7.0
Range :  19.39